Repository scikit-learn-contrib/MAPIE, pull requests merged in 2021-06, with the labels that each got.

#50 Cv prefit
  .appveyor.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  HISTORY.rst
  doc/images/quickstart_1.png
  doc/tutorial.rst
  examples/plot_homoscedastic_1d_data.py
  examples/plot_nested-cv.py
  examples/plot_prefit_nn.py
  examples/plot_toy_model.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
  mapie/tests/test_utils.py
  mapie/utils.py
Labels: documentation, enhancement

#51 enforce 80-character line length
  .flake8
  README.rst
  examples/plot_barber2020_simulations.py
  examples/plot_nested-cv.py
  examples/plot_prefit_nn.py
  examples/plot_toy_model.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
  mapie/tests/test_metrics.py
  mapie/tests/test_utils.py
  mapie/utils.py
  setup.py
Labels: enhancement

#52 Update tutorial and figures
  doc/images/quickstart_1.png
  doc/images/tuto_1.png
  doc/images/tuto_2.png
  doc/images/tuto_3.png
  doc/images/tuto_4.png
  doc/images/tuto_5.png
  doc/images/tuto_6.png
  doc/images/tuto_7.png
  doc/images/tuto_8.png
  doc/images/tuto_9.png
  doc/tutorial.rst
Labels: documentation

#53 small changes
  doc/quick_start.rst
  examples/plot_toy_model.py
  mapie/estimators.py
Labels: documentation, enhancement

#54 Ci GitHub
  .appveyor.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .travis.yml
  HISTORY.rst
  README.rst
  RELEASE_CHECKLIST.md
  doc/images/mapie_internals.png
  doc/images/quickstart_1.png
  doc/theoretical_description.rst
  examples/plot_barber2020_simulations.py
  examples/plot_nested-cv.py
  mapie/estimators.py
Labels: documentation, enhancement

#55 Update readthedocs yml file
  .readthedocs.yml
  README.rst
Labels: documentation

#56 Move alpha to predict and make corrections in tests, examples, and docs
  HISTORY.rst
  README.rst
  doc/images/quickstart_1.png
  doc/quick_start.rst
  doc/tutorial.rst
  examples/plot_barber2020_simulations.py
  examples/plot_homoscedastic_1d_data.py
  examples/plot_nested-cv.py
  examples/plot_prefit_nn.py
  examples/plot_toy_model.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
Labels: documentation, enhancement

#58 Typos
  doc/theoretical_description.rst
  examples/plot_barber2020_simulations.py
  examples/plot_nested-cv.py
  mapie/estimators.py
Labels: documentation

#59 Fix nested-cv figure
  examples/plot_nested-cv.py
Labels: bug

#61 Add TS and epistemic uncertainty examples
  .circleci/config.yml
  doc/environment.yml
  examples/data/demand_temperature.csv
  examples/plot_both_uncertainties.py
  examples/plot_timeseries_example.py
Labels: documentation, enhancement
