Repository scikit-learn-contrib/MAPIE, pull requests merged in 2021-05, with the labels that each got.

#35 move all alpha-related operations to predict
  .github/PULL_REQUEST_TEMPLATE.md
  AUTHORS.rst
  CONTRIBUTING.rst
  HISTORY.rst
  RELEASE_CHECKLIST.md
  examples/plot_barber2020_simulations.py
  examples/plot_homoscedastic_1d_data.py
  examples/plot_nested-cv.py
  mapie/__init__.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
Labels: documentation, enhancement

#37 Add mapie logo
  README.rst
  doc/conf.py
  doc/images/mapie_logo_nobg_cut.png
  doc/images/mapie_logo_white_cut.png
Labels: documentation

#38 Change return pred
  HISTORY.rst
  doc/tutorial.rst
  examples/plot_barber2020_simulations.py
  examples/plot_homoscedastic_1d_data.py
  examples/plot_nested-cv.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
Labels: documentation, enhancement

#40 Improve documentation
  AUTHORS.rst
  HISTORY.rst
  doc/theoretical_description.rst
  doc/tutorial.rst
  examples/plot_barber2020_simulations.py
  examples/plot_nested-cv.py
Labels: documentation

#41 Update Makefile to copy quickstart image in images/ folder
  doc/Makefile
Labels: documentation

#39 Cv option
  .pep8speaks.yml
  HISTORY.rst
  README.rst
  RELEASE_CHECKLIST.md
  doc/_templates/class.rst
  doc/api.rst
  doc/quick_start.rst
  doc/tutorial.rst
  examples/plot_barber2020_simulations.py
  examples/plot_homoscedastic_1d_data.py
  examples/plot_nested-cv.py
  examples/plot_toy_model.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
Labels: documentation, enhancement

#42 add cv=-1 option
  .circleci/config.yml
  HISTORY.rst
  doc/images/quickstart_1.png
  doc/tutorial.rst
  examples/plot_homoscedastic_1d_data.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
Labels: documentation, enhancement

#44 Include njobs
  HISTORY.rst
  doc/images/quickstart_1.png
  examples/plot_barber2020_simulations.py
  examples/plot_homoscedastic_1d_data.py
  examples/plot_nested-cv.py
  examples/plot_toy_model.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
Labels: enhancement

#45 document and simplify parallelism
  mapie/estimators.py
Labels: documentation, enhancement

#46 refactorize doc
  README.rst
  RELEASE_CHECKLIST.md
  doc/environment.yml
  doc/images/quickstart_1.png
  doc/index.rst
Labels: documentation

#43 Accept alpha as a list or np.ndarray
  HISTORY.rst
  README.rst
  doc/images/quickstart_1.png
  doc/quick_start.rst
  doc/tutorial.rst
  examples/plot_barber2020_simulations.py
  examples/plot_homoscedastic_1d_data.py
  examples/plot_nested-cv.py
  examples/plot_toy_model.py
  mapie/estimators.py
  mapie/tests/test_estimators.py
Labels: documentation, enhancement
