Repository scikit-learn-contrib/MAPIE, pull requests merged in 2022-06, with the labels that each got.

#135 [ADD] EnbPI
  .gitignore
  HISTORY.rst
  README.rst
  doc/images/quickstart_1.png
  examples/regression/1-quickstart/plot_timeseries_example.py
  examples/regression/2-advanced-analysis/plot_timeseries_enbpi.py
  mapie/_compatibility.py
  mapie/regression.py
  mapie/subsample.py
  mapie/tests/test_regression.py
  mapie/tests/test_subsample.py
  mapie/tests/test_time_series_regression.py
  mapie/tests/test_utils.py
  mapie/time_series_regression.py
  mapie/utils.py
  notebooks/regression/ts-changepoint.ipynb
  notebooks/regression/ts-changepoint.md
Labels: enhancement

#146 Feat/allow custom score function
  AUTHORS.rst
  README.rst
  doc/theoretical_description_regression.rst
  examples/regression/1-quickstart/plot_compare_conformity_scores.py
  examples/regression/1-quickstart/plot_prefit_nn.py
  examples/regression/1-quickstart/plot_timeseries_example.py
  examples/regression/2-advanced-analysis/plot_nested-cv.py
  examples/regression/3-scientific-articles/plot_kim2020_simulations.py
  mapie/conformity_scores.py
  mapie/regression.py
  mapie/tests/test_conformity_scores.py
  mapie/tests/test_regression.py
  mapie/utils.py
Labels: enhancement

#180 Doc enbpi
  HISTORY.rst
  README.rst
  doc/images/comp-methods.csv
  doc/images/quickstart_1.png
  doc/theoretical_description_regression.rst
Labels: documentation

#175 Update theoretical description and fix bugs in classification tutorial
  doc/api.rst
  doc/images/classification_methods.png
  doc/theoretical_description_classification.rst
  doc/tutorial_classification.rst
  doc/tutorial_classification_files/tutorial_classification_28_0.png
  doc/tutorial_regression.rst
  doc/tutorial_regression_files/tutorial_regression_73_0.png
  doc/tutorial_regression_files/tutorial_regression_74_0.png
  notebooks/classification/tutorial_classification.md
  notebooks/regression/tutorial_regression.ipynb
  notebooks/regression/tutorial_regression.md
Labels: documentation

#188 Add 'packaging' library into requirements in setup.py
  setup.py
Labels: bug
