Repository scikit-learn-contrib/MAPIE, pull requests merged in 2023-09, with the labels that each got.

#332 Add documentation for adaptive metrics and CRF score
  doc/api.rst
  doc/index.rst
  doc/theoretical_description_conformity_scores.rst
  doc/theoretical_description_regression.rst
  examples/regression/2-advanced-analysis/plot_conditional_coverage.py
  examples/regression/4-tutorials/plot_cqr_tutorial.py
  examples/regression/4-tutorials/plot_crf_tutorial.py
  mapie/conformity_scores/residual_conformity_scores.py
  mapie/metrics.py
Labels: documentation

#329 Add calibration statistics
  CONTRIBUTING.rst
  HISTORY.rst
  Makefile
  doc/api.rst
  doc/index.rst
  doc/theoretical_description_calibration.rst
  examples/calibration/1-quickstart/README.rst
  examples/calibration/1-quickstart/calibration_hypothesis_testing.py
  examples/calibration/2-advanced-analysis/README.rst
  examples/calibration/2-advanced-analysis/asymptotic_convergence_of_p_values.py
  examples/calibration/README.rst
  mapie/metrics.py
  mapie/tests/test_metrics.py
Labels: enhancement

#324 ENH: prediction sets for binary classification
  HISTORY.rst
  doc/index.rst
  doc/theoretical_description_binary_classification.rst
  examples/classification/4-tutorials/plot_main-tutorial-binary-classification.py
  mapie/classification.py
  mapie/tests/test_classification.py
Labels: enhancement

#352 FIX doc on calibration
  doc/Makefile
  doc/conf.py
  doc/theoretical_description_calibration.rst
  examples/calibration/1-quickstart/calibration_hypothesis_testing.py
  examples/calibration/2-advanced-analysis/asymptotic_convergence_of_p_values.py
  examples/calibration/README.rst
Labels: documentation

#344 DOC: update the MAPIE homepage
  README.rst
  doc/conf.py
  doc/images/cp_cross.png
  doc/images/cp_prefit.png
  doc/images/cp_split.png
  doc/images/quickstart_2.png
  doc/index.rst
  doc/quick_start.rst
  doc/split_cross_conformal.rst
Labels: documentation

#347 ADD documentation/Tutorial for learn then test
  HISTORY.rst
  doc/index.rst
  doc/notebooks_multilabel_classification.rst
  doc/theoretical_description_multilabel_classification.rst
  examples/multilabel_classification/1-quickstart/plot_tutorial_multilabel_classification.py
  notebooks/classification/tutorial_multilabel_classification.ipynb
  notebooks/classification/tutorial_multilabel_classification_precision.ipynb
  notebooks/classification/tutorial_multilabel_classification_recall.ipynb
Labels: documentation

#359 UPD: sign of normalized residual conformity scores
  mapie/conformity_scores/residual_conformity_scores.py
Labels: bug

#360 UPD: minor changes of binary classification page
  doc/theoretical_description_binary_classification.rst
Labels: documentation

#361 ADD: Conformal Predictive Distribution example
  examples/regression/2-advanced-analysis/plot_conformal_predictive_distribution.py
Labels: documentation
