Repository scikit-learn-contrib/MAPIE, pull requests merged in 2023-04, with the labels that each got.

#296 ENH: Add the split strategy to regression class
  HISTORY.rst
  mapie/calibration.py
  mapie/classification.py
  mapie/regression.py
  mapie/tests/test_calibration.py
  mapie/tests/test_classification.py
  mapie/tests/test_regression.py
  mapie/time_series_regression.py
  mapie/utils.py
Labels: enhancement

#295 294 get an error when the number of labels in calibration is not the same as during the training when using cv=prefit
  mapie/classification.py
  mapie/tests/test_classification.py
Labels: bug

#303 Update setup.py
  setup.py
Labels: invalid

#302 UPD: docstring of regression classes
  mapie/quantile_regression.py
  mapie/regression.py
  mapie/tests/test_quantile_regression.py
  mapie/time_series_regression.py
Labels: documentation
