Repository scikit-learn-contrib/MAPIE, pull requests merged in 2024-01, with the labels that each got.

#341 Add Adaptive Conformal Inference method for Time Series
  AUTHORS.rst
  HISTORY.rst
  doc/notebooks_regression.rst
  examples/regression/2-advanced-analysis/plot-coverage-width-based-criterion.py
  examples/regression/3-scientific-articles/plot_zaffran2022_comparison.py
  examples/regression/4-tutorials/plot_ts-tutorial.py
  mapie/conformity_scores/conformity_scores.py
  mapie/metrics.py
  mapie/regression/quantile_regression.py
  mapie/regression/regression.py
  mapie/regression/time_series_regression.py
  mapie/tests/test_metrics.py
  mapie/tests/test_regression.py
  mapie/tests/test_time_series_regression.py
  mapie/tests/test_utils.py
  mapie/utils.py
  notebooks/regression/ts-changepoint.ipynb
Labels: enhancement, developers

#396 FIX: Remove pandas in package import
  examples/regression/4-tutorials/plot_ts-tutorial.py
  mapie/regression/time_series_regression.py
  mapie/tests/test_utils.py
  mapie/utils.py
  notebooks/regression/ts-changepoint.ipynb
Labels: bug, developers

#391 Add fit parameters passing
  AUTHORS.rst
  HISTORY.rst
  mapie/calibration.py
  mapie/classification.py
  mapie/estimator/estimator.py
  mapie/estimator/interface.py
  mapie/regression/quantile_regression.py
  mapie/regression/regression.py
  mapie/tests/test_calibration.py
  mapie/tests/test_classification.py
  mapie/tests/test_quantile_regression.py
  mapie/tests/test_regression.py
  mapie/utils.py
Labels: enhancement, contributors
